`Numpy `*library is used for numerical computations and data analysis. It provides support for large, multi-dimensional arrays and matrices , and is the foundation of most scientific computing in Python. Numpy arrays are similar to Python lists , but they are more efficient and provide additional functionality.*

In [1]:
# import librray
import numpy as np

`Array` *is data structure that can store multiple values of different data types. It is a collection of items that can be of any data type, including strings, integers, floats, and other arrays. The items in an array are called elements or entries.*

In [2]:
# array of 6 elements
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [6]:
a.shape

(6,)

In [4]:
# 2 dimmensional array
q_2=a[np.newaxis, :]
print(q_2)

[[0 1 2 3 4 5]]


In [5]:
q_2.shape

(1, 6)

In [8]:
q_2=a[: , np.newaxis]
print(q_2)
q_2.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [9]:
# create array 
a=np.array([1,2,3,4,5,6]) # 1D array
b=np.array([[1,2,3],[4,5,6]]) # 2D array

In [11]:
print("1D ARRAY ", a.shape)
print("2D ARRAY ", b.shape)

1D ARRAY  (6,)
2D ARRAY  (2, 3)


In [18]:
type(a)

numpy.ndarray

In [12]:
# intialize array
zeros=np.zeros((2,3)) # 2 rows and 3 columns
print(zeros) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
one=np.ones((2,3)) # 2 rows and 3 columns
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# full array
full=np.full((2,3), 2) # 2 rows and 3 columns
full

array([[2, 2, 2],
       [2, 2, 2]])

In [17]:
full.dtype

dtype('int64')

In [19]:
type(full)

numpy.ndarray

In [15]:
# identity matrix
identity=np.eye(3) # 3x3 identity matrix
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
identity.dtype

dtype('float64')

In [20]:
type(identity)

numpy.ndarray

In [ ]:
# attributes of array 

In [ ]:
identity.shape # shape of the array

(3, 3)

In [ ]:
len(identity) # number of rows

3

In [23]:
identity.ndim  # number of dimensions

2

In [24]:
identity.size # total number of elements

9

In [26]:
# basic operations
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
c=a+b # element wise addition
print(c)

[ 8 10 12 14 16 18]


In [27]:
# basic operations
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
d=a-b # element wise subtraction
print(d)

[-6 -6 -6 -6 -6 -6]


In [28]:
# basic operations
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
m=a*b # element wise multiplication
print(m)

[ 7 16 27 40 55 72]


In [29]:
# basic operations
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])
div=a/b # element wise division
print(div)

[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [ ]:
a=np.arange(6)
b=a**2 # element wise squaring
print(b)

[ 0  1  4  9 16 25]


In [35]:
# empty array 
empty=np.empty((2,4)) # 2 rows and 3 columns
print(empty)

[[0.000e+000 0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 1.099e-320 0.000e+000 0.000e+000]]


In [34]:
print(empty[0]) # access first row

[3.5e-323 4.0e-323 4.4e-323]


In [38]:
np.arange(6,18,2) # start at 6, end at 18, step by 2

array([ 6,  8, 10, 12, 14, 16])

In [39]:
# array of odd numbers
odd_numbers = np.arange(1, 20, 2)  # start at 1, end at 20, step by 2
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]


In [40]:
# difference between numbers
diff= np.arange(1, 20, 0.5)  # start at 1, end at 20, step by 0.5 
print(diff)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [43]:
# linespace (linear trends # between two numbers) 
lin= np.linspace(0, 10, num=5)  # start at 1, end at 10, 5 points
print(lin)

[ 0.   2.5  5.   7.5 10. ]


In [44]:
lin= np.linspace(0, -10, num=5, endpoint=False)
print(lin)

[ 0. -2. -4. -6. -8.]


In [46]:
lin.dtype

dtype('float64')

In [ ]:
# define data type of array 
x=np.array([1,2,3,4,5,6], dtype=np.float64) # 1D array with float64 data type
print(x)

[1. 2. 3. 4. 5. 6.]


In [47]:
y=np.arange(6, dtype=np.int64) # 1D array with int64 data type
print(y)

[0 1 2 3 4 5]


In [48]:
# sorting an array 
sorted_array = np.sort(y)  # sort the array in ascending order
print(sorted_array)

[0 1 2 3 4 5]


In [49]:
# argsort returns the indices that would sort the array
argsorted_indices = np.argsort(y)  # indices of the sorted array
print(argsorted_indices)

[0 1 2 3 4 5]


In [50]:
# concatenate arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b)) # concatenate a and b
print(c)

[1 2 3 4 5 6]


In [55]:
# concatenate arrays
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9]])

In [56]:
z=np.concatenate((x,y)) # concatenate x and y
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
# concatenate arrays
i=np.array([[1,2,3],[4,5,6]])
j=np.array([[7,8,9],[10,11,12]])
k=np.concatenate((i, j), axis=0) # concatenate i and j along rows
print(k)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [61]:
# 3d array
l=np.array([[[1,2,3],
             [4,5,6]],
            
            [[7,8,9],
             [10,11,12]] , 
            
            [[14,15,16],
             [17,18,19]]]) # 3D array
print(l)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[14 15 16]
  [17 18 19]]]


In [62]:
len(l)

3

In [63]:
l.size

18

In [64]:
l.shape  # shape of the array

(3, 2, 3)

In [65]:
# reshape array
n=np.array([1,2,3,4,5,6,7,8,9,10,11,12]) # 1D array
m=n.reshape((3,4)) # reshape to 3 rows and 4 columns
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
np.reshape(l, (3, 3, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[14, 15],
        [16, 17],
        [18, 19]]])

In [68]:
# convert to 2D array
l_2d = l.reshape(-1, 2)  # Reshape to 2D array with 2 columns
print(l_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [14 15]
 [16 17]
 [18 19]]


In [69]:
# indexing and slicing
a=np.array([1,2,3,4,5,6])
# Accessing elements
print(a[0])  # First element
print(a[1])  # Second element
print(a[-1])  # Last element
# Slicing
print(a[1:4])  # Elements from index 1 to 3 (exclusive of 4)
print(a[:3])  # First three elements
print(a[3:])  # Elements from index 3 to the end
# Boolean indexing
b = a > 3  # Boolean array where elements are greater than 3
print(b)

1
2
6
[2 3 4]
[1 2 3]
[4 5 6]
[False False False  True  True  True]


In [71]:
# use two conditions
result = (a > 3) & (a < 6)  # Elements greater than 3 and less than 6
print(result)
print(a[result])  # Show the elements that satisfy both conditions


[False False False  True  True False]
[4 5]


In [73]:
a[(a > 3) & (a < 6)]  # Elements greater than 3 and less than 6

array([4, 5])

In [74]:
a[(a > 3) & (a < 6)  & (a % 2 == 0)]  

array([4])

In [75]:
a[(a > 3) | (a < 6)]

array([1, 2, 3, 4, 5, 6])

In [77]:
# create  array from existing array
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)  # Reshape to 2 rows and 3 columns
print(b)

[[1 2 3]
 [4 5 6]]


In [79]:
# making an array from data another array
a=np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [80]:
arr=a[20:45]
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44]


In [83]:
b=np.array([1, 2, 3, 4, 5, 6])
c=np.array([7, 8, 9, 10, 11, 12])
d=np.vstack((b, c))  # Stack b and c vertically
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [85]:
e=np.hstack((b, c))
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [86]:
d=d.reshape(3, 4)  
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Matrix or Matrices

In [87]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [95]:
b = np.arange(0, 50, 2).reshape(5,5) 
print(b)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [97]:
b[:,:]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [98]:
b[1:,:]

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [99]:
b[1:3,:]

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [100]:
b[1:3,2:]

array([[14, 16, 18],
       [24, 26, 28]])

In [101]:
b[1:3,2:5]

array([[14, 16, 18],
       [24, 26, 28]])

In [103]:
# slicing a matric
c=b[1:3,3:5]
print(c)

[[16 18]
 [26 28]]


In [105]:
c.max()

np.int64(28)

In [106]:
c.min()

np.int64(16)

In [107]:
c.sum()

np.int64(88)

In [109]:
c.max(axis=1)

array([18, 28])

In [111]:
c.min(axis=0)

array([16, 18])

In [119]:
m=np.arange(0,50,5).reshape(5,2)
m

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [120]:
m + np.array([2, 5])

array([[ 2, 10],
       [12, 20],
       [22, 30],
       [32, 40],
       [42, 50]])

In [121]:
np.vstack(m + np.array([2, 5]))

array([[ 2, 10],
       [12, 20],
       [22, 30],
       [32, 40],
       [42, 50]])

In [122]:
np.hstack(m + np.array([2, 5]))

array([ 2, 10, 12, 20, 22, 30, 32, 40, 42, 50])

In [126]:
# generate random numbers
import random
random_numbers = [random.randint(1, 100) for _ in range(10)]
print(random_numbers)

[1, 34, 93, 25, 36, 89, 43, 54, 93, 67]
